package com.jelly.mightyminerv2.macro.impl.GlacialMacro;

import com.jelly.mightyminerv2.util.helper.MineableBlock;
import com.jelly.mightyminerv2.util.helper.route.RouteWaypoint;
import com.jelly.mightyminerv2.util.helper.route.WaypointType;
import com.jelly.mightyminerv2.util.BlockUtil;
import com.jelly.mightyminerv2.util.PlayerUtil;
import lombok.Getter;

import java.util.*;

/**
 * Enum representing the different types of Glacite veins and their properties.
 * Each vein has a display name and a drop name.
 */
public enum GlaciteVeins {

    TOPAZ("Topaz Gemstone", "Rough Topaz Gemstone", MineableBlock.TOPAZ),
    AMBER("Amber Gemstone", "Rough Amber Gemstone", MineableBlock.AMBER),
    SAPPHIRE("Sapphire Gemstone", "Rough Sapphire Gemstone", MineableBlock.SAPPHIRE),
    JADE("Jade Gemstone", "Rough Jade Gemstone", MineableBlock.JADE),
    AMETHYST("Amethyst Gemstone", "Rough Amethyst Gemstone", MineableBlock.AMETHYST),
    RUBY("Ruby Gemstone", "Rough Ruby Gemstone", MineableBlock.RUBY),
    AQUAMARINE("Aquamarine Gemstone", "Rough Aquamarine Gemstone", MineableBlock.AQUAMARINE),
    PERIDOT("Peridot Gemstone", "Rough Peridot Gemstone", MineableBlock.PERIDOT),
    ONYX("Onyx Gemstone", "Rough Onyx Gemstone", MineableBlock.ONYX),
    CITRINE("Citrine Gemstone", "Rough Citrine Gemstone", MineableBlock.CITRINE),
    GLACITE("Glacite", "Glacite", MineableBlock.GLACITE),
    UMBER("Umber", "Umber", MineableBlock.UMBER),
    TUNGSTEN("Tungsten", "Tungsten", MineableBlock.TUNGSTEN);

    @Getter
    private final String dropName;
    @Getter
    private final String displayName;
    @Getter
    private final List<MineableBlock> mineableBlocks;

    GlaciteVeins(String displayName, String dropName, MineableBlock... blocks) {
        this.displayName = displayName;
        this.dropName = dropName;
        this.mineableBlocks = Collections.unmodifiableList(Arrays.asList(blocks));
    }

    @Getter
    private static final Map<GlaciteVeins, String> DROP_NAMES_MAP;
    private static final Map<GlaciteVeins, RouteWaypoint[]> VEINS;

    static {
        EnumMap<GlaciteVeins, String> map = new EnumMap<>(GlaciteVeins.class);
        for (GlaciteVeins vein : GlaciteVeins.values()) {
            map.put(vein, vein.getDropName());
        }
        DROP_NAMES_MAP = Collections.unmodifiableMap(map);

        Map<GlaciteVeins, RouteWaypoint[]> routesMap = new EnumMap<GlaciteVeins, RouteWaypoint[]>(GlaciteVeins.class) {
            {
                put(PERIDOT, new RouteWaypoint[]{
                        new RouteWaypoint(-76, 120, 285, WaypointType.WALK),
                        new RouteWaypoint(-69, 120, 286, WaypointType.WALK),
                        new RouteWaypoint(-71, 120, 287, WaypointType.WALK),
                        new RouteWaypoint(-68, 122, 294, WaypointType.WALK),
                        new RouteWaypoint(-56, 131, 298, WaypointType.WALK),
                        new RouteWaypoint(-56, 131, 292, WaypointType.WALK),
                        new RouteWaypoint(-54, 132, 294, WaypointType.WALK),
                        new RouteWaypoint(-63, 132, 292, WaypointType.WALK),
                        new RouteWaypoint(-68, 132, 294, WaypointType.WALK),
                        new RouteWaypoint(-72, 133, 290, WaypointType.WALK),
                        new RouteWaypoint(-75, 134, 287, WaypointType.WALK),
                        new RouteWaypoint(-78, 140, 284, WaypointType.ETHERWARP),
                        new RouteWaypoint(-76, 145, 289, WaypointType.ETHERWARP),
                        new RouteWaypoint(-73, 145, 290, WaypointType.WALK),
                        new RouteWaypoint(-68, 145, 285, WaypointType.WALK),
                        new RouteWaypoint(-62, 146, 285, WaypointType.WALK),
                        new RouteWaypoint(-63, 146, 290, WaypointType.WALK),
                        new RouteWaypoint(-69, 146, 292, WaypointType.WALK),
                        new RouteWaypoint(-62, 146, 295, WaypointType.WALK),
                        new RouteWaypoint(-65, 146, 304, WaypointType.WALK),
                        new RouteWaypoint(91, 121, 399, WaypointType.WALK),
                        new RouteWaypoint(107, 123, 404, WaypointType.WALK),
                        new RouteWaypoint(105, 123, 401, WaypointType.WALK),
                        new RouteWaypoint(108, 123, 399, WaypointType.WALK),
                        new RouteWaypoint(110, 123, 399, WaypointType.WALK),
                        new RouteWaypoint(113, 124, 396, WaypointType.WALK),
                        new RouteWaypoint(115, 125, 388, WaypointType.WALK),
                        new RouteWaypoint(117, 125, 383, WaypointType.WALK),
                        new RouteWaypoint(119, 126, 381, WaypointType.WALK),
                        new RouteWaypoint(121, 125, 385, WaypointType.WALK),
                        new RouteWaypoint(94, 121, 402, WaypointType.WALK),
                        new RouteWaypoint(97, 122, 404, WaypointType.WALK),
                        new RouteWaypoint(100, 122, 402, WaypointType.WALK),
                        new RouteWaypoint(81, 120, 397, WaypointType.WALK),
                        new RouteWaypoint(-72, 122, 463, WaypointType.WALK),
                        new RouteWaypoint(-75, 122, 466, WaypointType.WALK),
                        new RouteWaypoint(-78, 122, 466, WaypointType.WALK),
                        new RouteWaypoint(-85, 123, 466, WaypointType.WALK),
                        new RouteWaypoint(-88, 123, 468, WaypointType.WALK),
                        new RouteWaypoint(-91, 123, 464, WaypointType.WALK),
                        new RouteWaypoint(-95, 123, 462, WaypointType.WALK),
                        new RouteWaypoint(-96, 123, 453, WaypointType.WALK),
                        new RouteWaypoint(-105, 122, 453, WaypointType.WALK),
                        new RouteWaypoint(-107, 123, 460, WaypointType.WALK),
                        new RouteWaypoint(-108, 124, 465, WaypointType.WALK),
                        new RouteWaypoint(-108, 125, 471, WaypointType.WALK),
                        new RouteWaypoint(-103, 125, 469, WaypointType.WALK),
                        new RouteWaypoint(-97, 125, 471, WaypointType.WALK),
                });
                put(UMBER, new RouteWaypoint[]{
                        new RouteWaypoint(-74, 118, 260, WaypointType.WALK),
                        new RouteWaypoint(-76, 119, 264, WaypointType.WALK),
                        new RouteWaypoint(-58, 119, 273, WaypointType.WALK),
                        new RouteWaypoint(-55, 119, 275, WaypointType.WALK),
                        new RouteWaypoint(-40, 121, 284, WaypointType.WALK),
                        new RouteWaypoint(-36, 121, 284, WaypointType.WALK),
                        new RouteWaypoint(107, 120, 306, WaypointType.WALK),
                        new RouteWaypoint(105, 120, 309, WaypointType.WALK),
                        new RouteWaypoint(98, 122, 348, WaypointType.WALK),
                        new RouteWaypoint(99, 125, 371, WaypointType.WALK),
                        new RouteWaypoint(85, 122, 388, WaypointType.WALK),
                        new RouteWaypoint(40, 120, 373, WaypointType.WALK),
                        new RouteWaypoint(46, 119, 378, WaypointType.WALK),
                        new RouteWaypoint(19, 122, 354, WaypointType.WALK),
                        new RouteWaypoint(32, 122, 357, WaypointType.WALK),
                        new RouteWaypoint(-3, 119, 452, WaypointType.WALK),
                        new RouteWaypoint(-25, 117, 465, WaypointType.WALK),
                        new RouteWaypoint(-88, 124, 451, WaypointType.WALK),
                        new RouteWaypoint(-107, 133, 394, WaypointType.WALK),
                        new RouteWaypoint(-79, 130, 380, WaypointType.WALK),
                        new RouteWaypoint(-51, 125, 370, WaypointType.WALK),
                        new RouteWaypoint(-48, 124, 366, WaypointType.WALK),
                        new RouteWaypoint(-45, 122, 356, WaypointType.WALK),
                        new RouteWaypoint(-59, 123, 343, WaypointType.WALK),
                        new RouteWaypoint(-67, 125, 344, WaypointType.WALK),
                        new RouteWaypoint(-96, 130, 353, WaypointType.WALK),
                        new RouteWaypoint(-100, 131, 355, WaypointType.WALK),
                        new RouteWaypoint(-69, 118, 260, WaypointType.WALK),
                        new RouteWaypoint(-2, 127, 315, WaypointType.WALK),
                        new RouteWaypoint(2, 126, 318, WaypointType.WALK),
                        new RouteWaypoint(6, 126, 316, WaypointType.WALK),
                        new RouteWaypoint(38, 134, 354, WaypointType.WALK),
                        new RouteWaypoint(82, 149, 348, WaypointType.WALK),
                        new RouteWaypoint(86, 150, 347, WaypointType.WALK),
                        new RouteWaypoint(103, 150, 336, WaypointType.WALK),
                        new RouteWaypoint(101, 150, 332, WaypointType.WALK),
                        new RouteWaypoint(95, 150, 326, WaypointType.WALK),
                        new RouteWaypoint(92, 150, 324, WaypointType.WALK),
                        new RouteWaypoint(70, 151, 324, WaypointType.WALK),
                        new RouteWaypoint(76, 147, 310, WaypointType.WALK),
                        new RouteWaypoint(95, 148, 296, WaypointType.WALK),
                        new RouteWaypoint(106, 154, 286, WaypointType.WALK),
                        new RouteWaypoint(103, 154, 285, WaypointType.WALK),
                        new RouteWaypoint(57, 141, 282, WaypointType.WALK),
                        new RouteWaypoint(7, 146, 324, WaypointType.WALK),
                        new RouteWaypoint(8, 147, 339, WaypointType.WALK),
                        new RouteWaypoint(9, 147, 336, WaypointType.WALK),
                        new RouteWaypoint(-8, 145, 366, WaypointType.WALK),
                        new RouteWaypoint(-97, 147, 302, WaypointType.WALK),
                        new RouteWaypoint(-4, 150, 297, WaypointType.WALK),
                        new RouteWaypoint(54, 150, 403, WaypointType.WALK),
                        new RouteWaypoint(48, 148, 404, WaypointType.WALK),
                        new RouteWaypoint(32, 144, 405, WaypointType.WALK),
                        new RouteWaypoint(22, 140, 416, WaypointType.WALK),
                        new RouteWaypoint(34, 124, 448, WaypointType.WALK),
                        new RouteWaypoint(42, 124, 444, WaypointType.WALK),
                        new RouteWaypoint(5, 147, 349, WaypointType.WALK),
                        new RouteWaypoint(20, 144, 274, WaypointType.WALK),
                        new RouteWaypoint(22, 144, 278, WaypointType.WALK),
                        new RouteWaypoint(24, 117, 266, WaypointType.WALK),
                        new RouteWaypoint(28, 116, 268, WaypointType.WALK),
                        new RouteWaypoint(76, 116, 269, WaypointType.WALK),
                        new RouteWaypoint(-76, 146, 391, WaypointType.WALK),
                        new RouteWaypoint(-76, 144, 398, WaypointType.WALK),
                        new RouteWaypoint(-72, 144, 404, WaypointType.ETHERWARP),
                        new RouteWaypoint(-73, 144, 397, WaypointType.ETHERWARP),
                        new RouteWaypoint(-72, 143, 408, WaypointType.WALK),
                        new RouteWaypoint(-76, 146, 409, WaypointType.ETHERWARP),
                        new RouteWaypoint(-70, 143, 416, WaypointType.WALK),
                        new RouteWaypoint(-81, 130, 402, WaypointType.WALK),
                        new RouteWaypoint(-72, 129, 401, WaypointType.WALK),
                });
                put(TUNGSTEN, new RouteWaypoint[]{
                        new RouteWaypoint(-54, 118, 242, WaypointType.WALK),
                        new RouteWaypoint(-58, 118, 245, WaypointType.WALK),
                        new RouteWaypoint(-63, 118, 247, WaypointType.WALK),
                        new RouteWaypoint(-59, 119, 279, WaypointType.WALK),
                        new RouteWaypoint(-55, 120, 283, WaypointType.WALK),
                        new RouteWaypoint(-52, 120, 287, WaypointType.WALK),
                        new RouteWaypoint(-50, 120, 291, WaypointType.WALK),
                        new RouteWaypoint(-16, 123, 276, WaypointType.WALK),
                        new RouteWaypoint(-12, 123, 277, WaypointType.WALK),
                        new RouteWaypoint(-8, 124, 279, WaypointType.WALK),
                        new RouteWaypoint(-5, 124, 282, WaypointType.WALK),
                        new RouteWaypoint(-2, 124, 285, WaypointType.WALK),
                        new RouteWaypoint(2, 125, 287, WaypointType.WALK),
                        new RouteWaypoint(5, 125, 288, WaypointType.WALK),
                        new RouteWaypoint(45, 114, 272, WaypointType.WALK),
                        new RouteWaypoint(49, 114, 272, WaypointType.WALK),
                        new RouteWaypoint(53, 114, 271, WaypointType.WALK),
                        new RouteWaypoint(90, 119, 324, WaypointType.WALK),
                        new RouteWaypoint(86, 118, 327, WaypointType.WALK),
                        new RouteWaypoint(83, 118, 331, WaypointType.WALK),
                        new RouteWaypoint(81, 117, 335, WaypointType.WALK),
                        new RouteWaypoint(80, 117, 339, WaypointType.WALK),
                        new RouteWaypoint(109, 123, 365, WaypointType.WALK),
                        new RouteWaypoint(109, 123, 360, WaypointType.WALK),
                        new RouteWaypoint(106, 123, 357, WaypointType.WALK),
                        new RouteWaypoint(102, 123, 355, WaypointType.WALK),
                        new RouteWaypoint(90, 126, 373, WaypointType.WALK),
                        new RouteWaypoint(87, 127, 372, WaypointType.WALK),
                        new RouteWaypoint(-86, 121, 287, WaypointType.WALK),
                        new RouteWaypoint(-85, 122, 291, WaypointType.WALK),
                        new RouteWaypoint(-83, 122, 294, WaypointType.WALK),
                        new RouteWaypoint(-106, 133, 350, WaypointType.WALK),
                        new RouteWaypoint(-103, 132, 350, WaypointType.WALK),
                        new RouteWaypoint(-100, 131, 348, WaypointType.WALK),
                        new RouteWaypoint(-62, 124, 348, WaypointType.WALK),
                        new RouteWaypoint(-58, 123, 347, WaypointType.WALK),
                        new RouteWaypoint(-54, 123, 346, WaypointType.WALK),
                        new RouteWaypoint(21, 126, 295, WaypointType.WALK),
                        new RouteWaypoint(25, 127, 298, WaypointType.WALK),
                        new RouteWaypoint(29, 128, 299, WaypointType.WALK),
                        new RouteWaypoint(32, 128, 300, WaypointType.WALK),
                        new RouteWaypoint(41, 120, 323, WaypointType.WALK),
                        new RouteWaypoint(37, 121, 324, WaypointType.WALK),
                        new RouteWaypoint(32, 122, 327, WaypointType.WALK),
                        new RouteWaypoint(28, 123, 329, WaypointType.WALK),
                        new RouteWaypoint(24, 123, 331, WaypointType.WALK),
                        new RouteWaypoint(-9, 127, 338, WaypointType.WALK),
                        new RouteWaypoint(-5, 126, 340, WaypointType.WALK),
                        new RouteWaypoint(-1, 126, 340, WaypointType.WALK),
                        new RouteWaypoint(2, 126, 339, WaypointType.WALK),
                        new RouteWaypoint(-112, 135, 377, WaypointType.WALK),
                        new RouteWaypoint(-111, 134, 381, WaypointType.WALK),
                        new RouteWaypoint(-110, 134, 386, WaypointType.WALK),
                        new RouteWaypoint(-110, 134, 387, WaypointType.WALK),
                        new RouteWaypoint(-42, 131, 397, WaypointType.WALK),
                        new RouteWaypoint(-46, 131, 394, WaypointType.WALK),
                        new RouteWaypoint(-50, 131, 392, WaypointType.WALK),
                        new RouteWaypoint(-70, 131, 361, WaypointType.WALK),
                        new RouteWaypoint(-67, 131, 365, WaypointType.WALK),
                        new RouteWaypoint(-66, 130, 369, WaypointType.WALK),
                        new RouteWaypoint(-59, 119, 450, WaypointType.WALK),
                        new RouteWaypoint(-64, 120, 448, WaypointType.WALK),
                        new RouteWaypoint(-69, 121, 447, WaypointType.WALK),
                        new RouteWaypoint(-74, 121, 447, WaypointType.WALK),
                        new RouteWaypoint(-49, 116, 462, WaypointType.WALK),
                        new RouteWaypoint(-44, 115, 463, WaypointType.WALK),
                        new RouteWaypoint(-39, 115, 465, WaypointType.WALK),
                        new RouteWaypoint(-34, 116, 465, WaypointType.WALK),
                        new RouteWaypoint(-3, 119, 457, WaypointType.WALK),
                        new RouteWaypoint(2, 120, 458, WaypointType.WALK),
                        new RouteWaypoint(6, 121, 459, WaypointType.WALK),
                        new RouteWaypoint(51, 123, 438, WaypointType.WALK),
                        new RouteWaypoint(53, 122, 435, WaypointType.WALK),
                        new RouteWaypoint(21, 122, 429, WaypointType.WALK),
                        new RouteWaypoint(23, 122, 425, WaypointType.WALK),
                        new RouteWaypoint(54, 133, 332, WaypointType.WALK),
                        new RouteWaypoint(54, 133, 327, WaypointType.WALK),
                        new RouteWaypoint(53, 132, 323, WaypointType.WALK),
                        new RouteWaypoint(-40, 147, 277, WaypointType.WALK),
                        new RouteWaypoint(-42, 145, 270, WaypointType.WALK),
                        new RouteWaypoint(-44, 144, 265, WaypointType.WALK),
                        new RouteWaypoint(-49, 145, 302, WaypointType.WALK),
                        new RouteWaypoint(-44, 146, 301, WaypointType.WALK),
                        new RouteWaypoint(-40, 147, 300, WaypointType.WALK),
                        new RouteWaypoint(-53, 147, 332, WaypointType.WALK),
                        new RouteWaypoint(-52, 148, 337, WaypointType.WALK),
                        new RouteWaypoint(-52, 147, 337, WaypointType.WALK),
                        new RouteWaypoint(-20, 129, 360, WaypointType.WALK),
                        new RouteWaypoint(-20, 130, 366, WaypointType.WALK),
                        new RouteWaypoint(-19, 131, 371, WaypointType.WALK),
                        new RouteWaypoint(82, 117, 297, WaypointType.WALK),
                        new RouteWaypoint(78, 116, 300, WaypointType.WALK),
                        new RouteWaypoint(-54, 124, 430, WaypointType.WALK),
                        new RouteWaypoint(-55, 124, 426, WaypointType.WALK),
                        new RouteWaypoint(-55, 124, 422, WaypointType.WALK),
                        new RouteWaypoint(-107, 148, 344, WaypointType.WALK),
                        new RouteWaypoint(-106, 148, 348, WaypointType.WALK),
                        new RouteWaypoint(-93, 149, 366, WaypointType.WALK),
                        new RouteWaypoint(-97, 150, 365, WaypointType.WALK),
                        new RouteWaypoint(-53, 142, 443, WaypointType.WALK),
                        new RouteWaypoint(-58, 143, 442, WaypointType.WALK),
                        new RouteWaypoint(-61, 143, 440, WaypointType.WALK),
                        new RouteWaypoint(-40, 141, 435, WaypointType.WALK),
                        new RouteWaypoint(-36, 141, 434, WaypointType.WALK),
                        new RouteWaypoint(-32, 142, 432, WaypointType.WALK),
                        new RouteWaypoint(8, 137, 415, WaypointType.WALK),
                        new RouteWaypoint(7, 137, 419, WaypointType.WALK),
                        new RouteWaypoint(67, 151, 331, WaypointType.WALK),
                        new RouteWaypoint(62, 152, 331, WaypointType.WALK),
                        new RouteWaypoint(58, 153, 331, WaypointType.WALK),
                        new RouteWaypoint(30, 153, 330, WaypointType.WALK),
                        new RouteWaypoint(23, 152, 331, WaypointType.WALK),
                        new RouteWaypoint(20, 151, 333, WaypointType.WALK),
                        new RouteWaypoint(29, 147, 340, WaypointType.WALK),
                        new RouteWaypoint(30, 146, 337, WaypointType.WALK),
                        new RouteWaypoint(34, 145, 339, WaypointType.WALK),
                        new RouteWaypoint(36, 144, 334, WaypointType.WALK),
                        new RouteWaypoint(43, 142, 326, WaypointType.WALK),
                        new RouteWaypoint(44, 143, 330, WaypointType.WALK),
                        new RouteWaypoint(25, 148, 341, WaypointType.WALK),
                        new RouteWaypoint(20, 150, 339, WaypointType.WALK),
                        new RouteWaypoint(46, 139, 264, WaypointType.WALK),
                        new RouteWaypoint(46, 139, 264, WaypointType.WALK),
                        new RouteWaypoint(-93, 147, 312, WaypointType.WALK),
                        new RouteWaypoint(-97, 148, 313, WaypointType.WALK),
                        new RouteWaypoint(-101, 149, 317, WaypointType.WALK),
                        new RouteWaypoint(-70, 147, 313, WaypointType.WALK),
                        new RouteWaypoint(-75, 147, 313, WaypointType.WALK),
                        new RouteWaypoint(-2, 147, 352, WaypointType.WALK),
                        new RouteWaypoint(-1, 147, 347, WaypointType.WALK),
                        new RouteWaypoint(0, 147, 343, WaypointType.WALK),
                        new RouteWaypoint(104, 151, 305, WaypointType.WALK),
                        new RouteWaypoint(107, 153, 302, WaypointType.WALK),
                        new RouteWaypoint(109, 153, 300, WaypointType.WALK),
                });
                put(TOPAZ, new RouteWaypoint[]{
                        new RouteWaypoint(65, 129, 380, WaypointType.WALK),
                        new RouteWaypoint(63, 129, 377, WaypointType.WALK),
                        new RouteWaypoint(60, 129, 379, WaypointType.WALK),
                        new RouteWaypoint(56, 129, 379, WaypointType.WALK),
                        new RouteWaypoint(56, 129, 382, WaypointType.WALK),
                        new RouteWaypoint(59, 129, 388, WaypointType.WALK),
                        new RouteWaypoint(61, 129, 390, WaypointType.WALK),
                        new RouteWaypoint(64, 129, 390, WaypointType.WALK),
                        new RouteWaypoint(66, 129, 387, WaypointType.WALK),
                });
                put(SAPPHIRE, new RouteWaypoint[]{
                        new RouteWaypoint(19, 119, 259, WaypointType.WALK),
                        new RouteWaypoint(29, 117, 264, WaypointType.WALK),
                        new RouteWaypoint(41, 115, 271, WaypointType.WALK),
                        new RouteWaypoint(63, 115, 271, WaypointType.WALK),
                        new RouteWaypoint(68, 116, 271, WaypointType.WALK),
                        new RouteWaypoint(73, 116, 270, WaypointType.WALK),
                        new RouteWaypoint(101, 116, 282, WaypointType.WALK),
                        new RouteWaypoint(-9, 126, 323, WaypointType.WALK),
                        new RouteWaypoint(8, 126, 315, WaypointType.WALK),
                        new RouteWaypoint(-49, 118, 241, WaypointType.WALK),
                        new RouteWaypoint(-69, 117, 252, WaypointType.WALK),
                        new RouteWaypoint(-75, 119, 270, WaypointType.WALK),
                        new RouteWaypoint(-88, 123, 298, WaypointType.WALK),
                });
                put(ONYX, new RouteWaypoint[]{
                        new RouteWaypoint(5, 126, 305, WaypointType.WALK),
                        new RouteWaypoint(1, 126, 301, WaypointType.WALK),
                        new RouteWaypoint(-3, 126, 295, WaypointType.WALK),
                        new RouteWaypoint(-10, 126, 295, WaypointType.WALK),
                        new RouteWaypoint(-6, 126, 298, WaypointType.WALK),
                        new RouteWaypoint(-11, 126, 306, WaypointType.WALK),
                        new RouteWaypoint(-17, 125, 311, WaypointType.WALK),
                        new RouteWaypoint(-25, 125, 309, WaypointType.WALK),
                        new RouteWaypoint(-22, 125, 307, WaypointType.WALK),
                        new RouteWaypoint(-28, 124, 301, WaypointType.WALK),
                        new RouteWaypoint(-23, 125, 301, WaypointType.WALK),
                        new RouteWaypoint(-71, 129, 403, WaypointType.WALK),
                        new RouteWaypoint(-69, 129, 413, WaypointType.WALK),
                        new RouteWaypoint(-72, 129, 413, WaypointType.WALK),
                        new RouteWaypoint(-74, 128, 421, WaypointType.WALK),
                        new RouteWaypoint(-75, 126, 434, WaypointType.WALK),
                        new RouteWaypoint(-69, 126, 434, WaypointType.WALK),
                        new RouteWaypoint(-62, 126, 434, WaypointType.WALK),
                        new RouteWaypoint(-65, 126, 432, WaypointType.WALK),
                        new RouteWaypoint(-9, 139, 431, WaypointType.WALK),
                        new RouteWaypoint(-1, 138, 433, WaypointType.WALK),
                        new RouteWaypoint(-3, 138, 440, WaypointType.WALK),
                        new RouteWaypoint(1, 138, 442, WaypointType.WALK),
                        new RouteWaypoint(4, 138, 445, WaypointType.WALK),
                        new RouteWaypoint(1, 138, 451, WaypointType.WALK),
                        new RouteWaypoint(1, 139, 455, WaypointType.WALK),
                        new RouteWaypoint(79, 118, 412, WaypointType.WALK),
                        new RouteWaypoint(80, 118, 413, WaypointType.WALK),
                        new RouteWaypoint(89, 119, 427, WaypointType.WALK),
                        new RouteWaypoint(96, 120, 433, WaypointType.WALK),
                        new RouteWaypoint(100, 120, 441, WaypointType.WALK),
                        new RouteWaypoint(87, 120, 438, WaypointType.WALK),
                        new RouteWaypoint(77, 118, 406, WaypointType.WALK),
                });
                put(JADE, new RouteWaypoint[]{
                        new RouteWaypoint(5, 147, 342, WaypointType.WALK),
                });
                put(GLACITE, new RouteWaypoint[]{
                        new RouteWaypoint(30, 134, 363, WaypointType.WALK),
                        new RouteWaypoint(20, 135, 365, WaypointType.WALK),
                        new RouteWaypoint(-3, 134, 374, WaypointType.WALK),
                        new RouteWaypoint(19, 136, 376, WaypointType.WALK),
                        new RouteWaypoint(-1, 136, 412, WaypointType.WALK),
                        new RouteWaypoint(-112, 135, 332, WaypointType.WALK),
                        new RouteWaypoint(-83, 119, 275, WaypointType.WALK),
                        new RouteWaypoint(35, 116, 269, WaypointType.WALK),
                        new RouteWaypoint(44, 114, 276, WaypointType.WALK),
                        new RouteWaypoint(50, 114, 280, WaypointType.WALK),
                        new RouteWaypoint(66, 116, 303, WaypointType.WALK),
                        new RouteWaypoint(88, 116, 288, WaypointType.WALK),
                        new RouteWaypoint(94, 116, 280, WaypointType.WALK),
                        new RouteWaypoint(90, 116, 278, WaypointType.WALK),
                        new RouteWaypoint(107, 117, 289, WaypointType.WALK),
                        new RouteWaypoint(104, 119, 295, WaypointType.WALK),
                        new RouteWaypoint(108, 119, 298, WaypointType.WALK),
                        new RouteWaypoint(101, 120, 309, WaypointType.WALK),
                        new RouteWaypoint(109, 120, 325, WaypointType.WALK),
                        new RouteWaypoint(-50, 118, 243, WaypointType.WALK),
                        new RouteWaypoint(-72, 118, 256, WaypointType.WALK),
                        new RouteWaypoint(-69, 119, 272, WaypointType.WALK),
                        new RouteWaypoint(-36, 121, 287, WaypointType.WALK),
                        new RouteWaypoint(-51, 123, 314, WaypointType.WALK),
                        new RouteWaypoint(-80, 126, 317, WaypointType.WALK),
                        new RouteWaypoint(-77, 127, 321, WaypointType.WALK),
                        new RouteWaypoint(-103, 134, 390, WaypointType.WALK),
                        new RouteWaypoint(-93, 131, 403, WaypointType.WALK),
                        new RouteWaypoint(-92, 128, 439, WaypointType.WALK),
                        new RouteWaypoint(-55, 118, 453, WaypointType.WALK),
                        new RouteWaypoint(-22, 118, 455, WaypointType.WALK),
                        new RouteWaypoint(-17, 118, 451, WaypointType.WALK),
                        new RouteWaypoint(14, 122, 453, WaypointType.WALK),
                        new RouteWaypoint(21, 123, 453, WaypointType.WALK),
                        new RouteWaypoint(47, 124, 446, WaypointType.WALK),
                        new RouteWaypoint(60, 119, 432, WaypointType.WALK),
                        new RouteWaypoint(60, 116, 416, WaypointType.WALK),
                        new RouteWaypoint(55, 116, 416, WaypointType.WALK),
                        new RouteWaypoint(50, 117, 417, WaypointType.WALK),
                        new RouteWaypoint(31, 121, 422, WaypointType.WALK),
                        new RouteWaypoint(27, 122, 430, WaypointType.WALK),
                        new RouteWaypoint(54, 116, 407, WaypointType.WALK),
                        new RouteWaypoint(59, 117, 400, WaypointType.WALK),
                        new RouteWaypoint(71, 118, 401, WaypointType.WALK),
                        new RouteWaypoint(74, 118, 412, WaypointType.WALK),
                        new RouteWaypoint(83, 119, 413, WaypointType.WALK),
                        new RouteWaypoint(90, 119, 423, WaypointType.WALK),
                        new RouteWaypoint(94, 124, 381, WaypointType.WALK),
                        new RouteWaypoint(109, 123, 379, WaypointType.WALK),
                        new RouteWaypoint(114, 123, 350, WaypointType.WALK),
                        new RouteWaypoint(97, 121, 350, WaypointType.WALK),
                        new RouteWaypoint(92, 121, 348, WaypointType.WALK),
                        new RouteWaypoint(79, 118, 343, WaypointType.WALK),
                        new RouteWaypoint(80, 117, 332, WaypointType.WALK),
                        new RouteWaypoint(83, 118, 326, WaypointType.WALK),
                        new RouteWaypoint(98, 120, 313, WaypointType.WALK),
                        new RouteWaypoint(61, 119, 361, WaypointType.WALK),
                        new RouteWaypoint(19, 144, 263, WaypointType.WALK),
                        new RouteWaypoint(23, 143, 262, WaypointType.WALK),
                        new RouteWaypoint(46, 139, 268, WaypointType.WALK),
                        new RouteWaypoint(61, 141, 278, WaypointType.WALK),
                        new RouteWaypoint(29, 144, 279, WaypointType.WALK),
                        new RouteWaypoint(27, 145, 297, WaypointType.WALK),
                        new RouteWaypoint(21, 148, 317, WaypointType.WALK),
                        new RouteWaypoint(28, 150, 320, WaypointType.WALK),
                        new RouteWaypoint(63, 152, 327, WaypointType.WALK),
                        new RouteWaypoint(3, 148, 302, WaypointType.WALK),
                        new RouteWaypoint(4, 147, 336, WaypointType.WALK),
                        new RouteWaypoint(7, 147, 330, WaypointType.WALK),
                        new RouteWaypoint(-33, 148, 302, WaypointType.WALK),
                        new RouteWaypoint(-28, 149, 293, WaypointType.WALK),
                        new RouteWaypoint(-44, 143, 255, WaypointType.WALK),
                        new RouteWaypoint(-59, 142, 241, WaypointType.WALK),
                        new RouteWaypoint(-93, 142, 267, WaypointType.WALK),
                        new RouteWaypoint(-108, 143, 265, WaypointType.WALK),
                        new RouteWaypoint(-113, 143, 283, WaypointType.WALK),
                        new RouteWaypoint(-53, 146, 311, WaypointType.WALK),
                        new RouteWaypoint(80, 147, 307, WaypointType.WALK),
                        new RouteWaypoint(81, 148, 316, WaypointType.WALK),
                        new RouteWaypoint(108, 153, 293, WaypointType.WALK),
                        new RouteWaypoint(55, 117, 312, WaypointType.WALK),
                        new RouteWaypoint(22, 123, 330, WaypointType.WALK),
                        new RouteWaypoint(13, 124, 338, WaypointType.WALK),
                        new RouteWaypoint(11, 124, 343, WaypointType.WALK),
                        new RouteWaypoint(-29, 124, 336, WaypointType.WALK),
                        new RouteWaypoint(-66, 129, 386, WaypointType.WALK),
                        new RouteWaypoint(-68, 128, 383, WaypointType.WALK),
                        new RouteWaypoint(-63, 129, 390, WaypointType.WALK),
                        new RouteWaypoint(79, 117, 331, WaypointType.WALK),
                        new RouteWaypoint(-23, 129, 358, WaypointType.WALK),
                        new RouteWaypoint(-41, 130, 403, WaypointType.WALK),
                        new RouteWaypoint(-48, 126, 420, WaypointType.WALK),
                        new RouteWaypoint(-36, 122, 435, WaypointType.WALK),
                        new RouteWaypoint(85, 150, 379, WaypointType.WALK),
                        new RouteWaypoint(102, 150, 395, WaypointType.WALK),
                        new RouteWaypoint(72, 150, 390, WaypointType.WALK),
                        new RouteWaypoint(-18, 122, 265, WaypointType.WALK),
                        new RouteWaypoint(-82, 126, 312, WaypointType.WALK),
                        new RouteWaypoint(48, 130, 309, WaypointType.WALK),
                        new RouteWaypoint(40, 130, 308, WaypointType.WALK),
                        new RouteWaypoint(49, 134, 350, WaypointType.WALK),
                        new RouteWaypoint(54, 133, 344, WaypointType.WALK),
                        new RouteWaypoint(70, 132, 367, WaypointType.WALK),
                        new RouteWaypoint(79, 129, 377, WaypointType.WALK),
                        new RouteWaypoint(33, 121, 361, WaypointType.WALK),
                });

                put(CITRINE, new RouteWaypoint[]{
                        new RouteWaypoint(-51, 125, 418, WaypointType.WALK),
                        new RouteWaypoint(-47, 126, 416, WaypointType.WALK),
                        new RouteWaypoint(-59, 131, 410, WaypointType.WALK),
                        new RouteWaypoint(-62, 130, 415, WaypointType.WALK),
                        new RouteWaypoint(-59, 131, 414, WaypointType.WALK),
                        new RouteWaypoint(-59, 143, 428, WaypointType.WALK),
                        new RouteWaypoint(-51, 142, 415, WaypointType.WALK),
                        new RouteWaypoint(-49, 142, 413, WaypointType.WALK),
                        new RouteWaypoint(-48, 142, 409, WaypointType.WALK),
                        new RouteWaypoint(-50, 142, 406, WaypointType.WALK),
                        new RouteWaypoint(-55, 142, 405, WaypointType.WALK),
                        new RouteWaypoint(-58, 142, 405, WaypointType.WALK),
                        new RouteWaypoint(-59, 142, 408, WaypointType.WALK),
                        new RouteWaypoint(-58, 142, 412, WaypointType.WALK),
                        new RouteWaypoint(29, 119, 390, WaypointType.WALK),
                        new RouteWaypoint(25, 119, 390, WaypointType.WALK),
                        new RouteWaypoint(23, 119, 392, WaypointType.WALK),
                        new RouteWaypoint(20, 119, 394, WaypointType.WALK),
                        new RouteWaypoint(19, 119, 399, WaypointType.WALK),
                        new RouteWaypoint(21, 119, 406, WaypointType.WALK),
                        new RouteWaypoint(29, 117, 401, WaypointType.WALK),
                        new RouteWaypoint(33, 117, 400, WaypointType.WALK),
                });
                put(AQUAMARINE, new RouteWaypoint[]{
                        new RouteWaypoint(43, 116, 301, WaypointType.WALK),
                        new RouteWaypoint(43, 116, 296, WaypointType.WALK),
                        new RouteWaypoint(40, 116, 298, WaypointType.WALK),
                        new RouteWaypoint(40, 115, 293, WaypointType.WALK),
                        new RouteWaypoint(34, 116, 290, WaypointType.WALK),
                        new RouteWaypoint(26, 116, 290, WaypointType.WALK),
                        new RouteWaypoint(27, 116, 280, WaypointType.WALK),
                        new RouteWaypoint(22, 115, 280, WaypointType.WALK),
                        new RouteWaypoint(23, 115, 277, WaypointType.WALK),
                        new RouteWaypoint(20, 114, 274, WaypointType.WALK),
                        new RouteWaypoint(50, 116, 302, WaypointType.WALK),
                        new RouteWaypoint(-16, 132, 382, WaypointType.WALK),
                        new RouteWaypoint(-10, 133, 380, WaypointType.WALK),
                        new RouteWaypoint(-17, 132, 379, WaypointType.WALK),
                        new RouteWaypoint(-14, 134, 396, WaypointType.WALK),
                        new RouteWaypoint(12, 137, 409, WaypointType.WALK),
                        new RouteWaypoint(21, 136, 387, WaypointType.WALK),
                        new RouteWaypoint(20, 136, 382, WaypointType.WALK),
                        new RouteWaypoint(15, 136, 365, WaypointType.WALK),
                        new RouteWaypoint(10, 136, 368, WaypointType.WALK),
                        new RouteWaypoint(2, 134, 370, WaypointType.WALK),
                        new RouteWaypoint(-19, 132, 393, WaypointType.WALK),
                });
                put(RUBY, new RouteWaypoint[]{ //FAKE DATA
                        new RouteWaypoint(-76,119,284, WaypointType.WALK),
                        new RouteWaypoint(-71,120,287, WaypointType.WALK),
                        new RouteWaypoint(-68,120,287, WaypointType.WALK),
                        new RouteWaypoint(-67,122,297, WaypointType.WALK),
                        new RouteWaypoint(-72,122,462, WaypointType.WALK),
                        new RouteWaypoint(-76,122,467, WaypointType.WALK),
                        new RouteWaypoint(-87,123,465, WaypointType.WALK),
                        new RouteWaypoint(-81,123,467, WaypointType.WALK),
                        new RouteWaypoint(-89,123,468, WaypointType.WALK),
                        new RouteWaypoint(-92,123,464, WaypointType.WALK),
                        new RouteWaypoint(-99,122,452, WaypointType.WALK),
                        new RouteWaypoint(-105,122,454, WaypointType.WALK),
                        new RouteWaypoint(-108,123,461, WaypointType.WALK),
                        new RouteWaypoint(-107,125,468, WaypointType.WALK),
                        new RouteWaypoint(-97,125,470, WaypointType.WALK),
                        new RouteWaypoint(71,143,282, WaypointType.WALK),
                        new RouteWaypoint(81,142,276, WaypointType.WALK),
                        new RouteWaypoint(79,142,269, WaypointType.WALK),
                        new RouteWaypoint(66,143,284, WaypointType.WALK),
                        new RouteWaypoint(96,153,283, WaypointType.WALK),
                        new RouteWaypoint(93,121,400, WaypointType.WALK),
                        new RouteWaypoint(99,122,403, WaypointType.WALK),
                        new RouteWaypoint(108,123,402, WaypointType.WALK),
                        new RouteWaypoint(112,124,396, WaypointType.WALK),
                        new RouteWaypoint(115,125,387, WaypointType.WALK),
                        new RouteWaypoint(118,125,383, WaypointType.WALK),
                        new RouteWaypoint(121,125,386, WaypointType.WALK),
                });
                put(AMBER, new RouteWaypoint[]{
                        new RouteWaypoint(53, 114, 278, WaypointType.WALK),
                        new RouteWaypoint(109, 119, 296, WaypointType.WALK),
                        new RouteWaypoint(106, 120, 316, WaypointType.WALK),
                        new RouteWaypoint(46, 118, 393, WaypointType.WALK),
                        new RouteWaypoint(50, 118, 390, WaypointType.WALK),
                        new RouteWaypoint(40, 119, 377, WaypointType.WALK),
                        new RouteWaypoint(46, 119, 372, WaypointType.WALK),
                        new RouteWaypoint(39, 121, 360, WaypointType.WALK),
                        new RouteWaypoint(46, 120, 362, WaypointType.WALK),
                        new RouteWaypoint(-70, 126, 319, WaypointType.WALK),
                        new RouteWaypoint(-66, 126, 318, WaypointType.WALK),
                        new RouteWaypoint(-70, 127, 327, WaypointType.WALK),
                        new RouteWaypoint(-17, 141, 434, WaypointType.WALK),
                        new RouteWaypoint(-27, 141, 436, WaypointType.WALK),
                        new RouteWaypoint(-61, 143, 440, WaypointType.WALK),
                });
                put(AMETHYST, new RouteWaypoint[]{   //FAKE DATA
                        new RouteWaypoint(63,115,271, WaypointType.WALK),
                        new RouteWaypoint(84,116,275, WaypointType.WALK),
                        new RouteWaypoint(99,116,280, WaypointType.WALK),
                        new RouteWaypoint(-88,122,297, WaypointType.WALK),
                        new RouteWaypoint(-16,122,264, WaypointType.WALK),
                        new RouteWaypoint(-76,119,271, WaypointType.WALK),
                        new RouteWaypoint(-89,125,445, WaypointType.WALK),
                        new RouteWaypoint(1,148,249, WaypointType.WALK),
                        new RouteWaypoint(5,148,260, WaypointType.WALK),
                        new RouteWaypoint(18,144,268, WaypointType.WALK),
                        new RouteWaypoint(97,148,297, WaypointType.WALK),
                        new RouteWaypoint(103,151,304, WaypointType.WALK),
                        new RouteWaypoint(-47,118,240, WaypointType.WALK),
                });
            }};
        VEINS = Collections.unmodifiableMap(routesMap);
    }

    public static RouteWaypoint[] getVeins(GlaciteVeins vein) {
        return VEINS.get(vein);
    }

    public static RouteWaypoint findClosestWaypoint() {
        RouteWaypoint closestWaypoint = null;
        double closestDistance = Double.MAX_VALUE;
        for (RouteWaypoint waypoint : VEINS.get(GLACITE)) {
            double distance = waypoint.distanceTo(PlayerUtil.getBlockStandingOn());
            System.out.println("Distance: " + distance + " to " + waypoint);
            if (distance < 3) return waypoint;

            if (distance < closestDistance) {
                closestDistance = distance;
                closestWaypoint = waypoint;
            }
        }
        return closestWaypoint;
    }

    public static int getStateId(GlaciteVeins vein) {
        return MineableBlock.values()[15 + vein.ordinal()].stateIds.get(0);
    }

    public static int ticksToMine(GlaciteVeins vein, int miningSpeed) {
        int stateId = MineableBlock.values()[15 + vein.ordinal()].stateIds.get(0);
        if (stateId == 0) return 0;

        return BlockUtil.getMiningTime(stateId, miningSpeed);
    }

    public static GlaciteVeins getVeinFromName(String name) {
        for (GlaciteVeins vein : GlaciteVeins.values()) {
            if (vein.displayName.toLowerCase().contains(name.toLowerCase())) {
                return vein;
            }
        }
        return null;
    }
}
